version: 2.1

orbs:
  project: bigbite/project@1.2.1

jobs:
  build:
    executor:
      name: project/default
      php: '8.2'
    steps:
      - checkout
      - project/setup
      - project/composer-install
      - project/phpcs
      - project/phpstan
      - project/npm-install
      - project/npm-build
      - project/create-build

workflows:
  workflow:
    jobs:
      - build:
          context: bigbite
          filters:
            branches:
              ignore: /^.*-built$/
