<?php
/**
 * phpcs:ignoreFile -- As this file is auto-generated, it should be excluded from linting.
 *
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'BIGBITE_IMAGE_COMPARISON_EDITOR_CSS', 'editor-9c8d9590.css' );
define( 'BIGBITE_IMAGE_COMPARISON_EDITOR_JS', 'editor-646ad034.js' );
define( 'BIGBITE_IMAGE_COMPARISON_FRONTEND_CSS', 'frontend-88ed25b4.css' );
define( 'BIGBITE_IMAGE_COMPARISON_FRONTEND_JS', 'frontend-896f4274.js' );
define( 'BIGBITE_IMAGE_COMPARISON_SHARED_JS', 'shared-31d6cfe0.js' );
define( 'BIGBITE_IMAGE_COMPARISON_SHARED_CSS', 'shared-47cfbc96.css' );

define( 'BIGBITE_IMAGE_COMPARISON_EDITOR_DEPENDENCIES', ["wp-block-editor","wp-blocks","wp-components","wp-i18n"] );

define( 'BIGBITE_IMAGE_COMPARISON_FRONTEND_DEPENDENCIES', [] );
define( 'BIGBITE_IMAGE_COMPARISON_SHARED_DEPENDENCIES', [] );

define( 'BIGBITE_IMAGE_COMPARISON_VERSION', '0.0.1' );
